name = "casamx-app"
main = "cloudflare-worker.js"
compatibility_date = "2024-10-01"

[env.production]
name = "casamx-app"
routes = [
  { pattern = "casamx.app/*", zone_name = "casamx.app" },
  { pattern = "www.casamx.app/*", zone_name = "casamx.app" }
]