# CasaMX Prometheus Configuration
# Monitoring for production deployment

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'casamx-monitor'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Rule files for alerts
rule_files:
  - "alert_rules.yml"

# Scrape configuration
scrape_configs:
  # CasaMX Application
  - job_name: 'casamx-app'
    static_configs:
      - targets: ['casamx-app:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s
    
  # Redis monitoring
  - job_name: 'redis'
    static_configs:
      - targets: ['casamx-redis:6379']
    metrics_path: /metrics
    scrape_interval: 30s

  # Nginx monitoring
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:8080']
    metrics_path: /nginx_status
    scrape_interval: 30s

  # Node exporter (system metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 15s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['localhost:9323']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Custom application metrics
  - job_name: 'casamx-custom'
    static_configs:
      - targets: ['casamx-app:8000']
    metrics_path: /custom-metrics
    scrape_interval: 60s
    honor_labels: true