[build]
  publish = "dist"
  command = "python -m streamlit run streamlit_app.py --server.port 8080 &"
  
[build.environment]
  PYTHON_VERSION = "3.9"
  STREAMLIT_SERVER_PORT = "8080"
  STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"

[[plugins]]
  package = "netlify-plugin-python"

[context.production]
  command = "pip install -r requirements_netlify.txt && streamlit run streamlit_app.py --server.port 8080 --server.address 0.0.0.0"

[context.deploy-preview]
  command = "pip install -r requirements_netlify.txt && streamlit run streamlit_app.py --server.port 8080 --server.address 0.0.0.0"

# Custom domain configuration
[[redirects]]
  from = "/*"
  to = "/streamlit_app.py"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:;"

# Custom domain settings
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Caching rules for performance
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Domain configuration
[site]
  name = "casamx-store"