# Streamlit Configuration for Production
# CasaMX - Datatón ITAM 2025

[server]
# Configuración del servidor
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8080
address = "0.0.0.0"

[browser]
# Configuración del navegador
gatherUsageStats = false
showErrorDetails = false

[theme]
# Tema personalizado para CasaMX
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
# Configuración del cliente
showErrorDetails = false
toolbarMode = "minimal"

[logger]
# Configuración de logs
level = "info"

[global]
# Configuraciones globales
developmentMode = false
dataFrameSerialization = "legacy"